### ISSUE TITLE
Fixbug:add pictures in the article.

### ISSUE THREAD

**Issue by Ross0101** [caojiele/caojiele.github.io#5]
Fixbug:add pictures in the [article](https://github.com/Ross0101/caojiele.github.io/blob/master/_posts/2018-09-21-alibaba-nacos-discovery1.md).

**Comment by caojiele** [comment]
> Fixbug:add pictures in the [article](https://github.com/Ross0101/caojiele.github.io/blob/master/_posts/2018-09-21-alibaba-nacos-discovery1.md).

Good issue, can you resolve it?

**Comment by Ross0101** [comment]
> > Fixbug:add pictures in the [article](https://github.com/Ross0101/caojiele.github.io/blob/master/_posts/2018-09-21-alibaba-nacos-discovery1.md).
> 
> Good issue, can you resolve it?

OK, let me try it.
